
# Set R and packages
```{r setup}

rm(list=ls()) # Clear workspace
knitr::opts_knit$set(root.dir = '/tmp') #Set directory at current directory for all subsequent chunks

library(tidyverse)
library(panelr) # Convert data from wide to long
library(lubridate) # Date calculations
library(rstatix)
library(glmmTMB) # Nested beta regression
library(DHARMa) # Nested model validation
library(car) # ANOVA results GLM
library(emmeans) # Post hoccing
library(ggpubr)
library(ggplot2)
library(ggthemes) # Pretty plots
library(ggpattern) # Pretty bar plots
library(NCmisc) # Check packages used

#library(ggfortify)
#library(MuMIn)
#library(olsrr)
#library(dplyr)
#library(broom)
#library(tidyr)
#library(AICcmodavg)
#library(lme4)
#library(nlme)
#library(gratia)
#library(mgcv)
#library(lsmeans)
#library(lmerTest)
#library(magrittr) # for piping
#library(ggeffects) # Plot marginal effects



# Function to facilitate averaging dataset
data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE),
      n  = length(x[[col]]),
      se = sd(x[[col]], na.rm=TRUE)/sqrt(length(x)))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- plyr::rename(data_sum, c("mean" = varname))
 return(data_sum)
}

```

# Load and organize
```{r prepare data}

# Read in raw data
df0.raw <- read.csv("Bleaching_Mineral accretion bleaching.csv", check.names = FALSE, header = TRUE, 
                    colClasses = c(Structure = "factor", Position = "factor", Species = "factor", Treatment = "factor"))

# Convert to long dataframe
df1.clean <- as.data.frame(long_panel(df0.raw, prefix = "_", begin = 0, end = 16, label_location = "end"))

# Drop columns
df1.clean <- subset(df1.clean, select = -c(wave, Experiment, Location, Position, Origin, Remarks, Comments))

# Drop empty dates
df1.clean <- df1.clean %>%
             drop_na(Date)

df2.bleach <- df1.clean %>%
              filter(Survival !="0")

# Calculate corrected Brightness
#! Choice of AVG brightness (not Green brightness)
df2.bleach$Brightness <- df2.bleach$AVG / df2.bleach$ControlAVG * 255

# Drop more columns
df2.bleach <- subset(df2.bleach, select = -c(AVG, R, G, B, ControlAVG, ControlR, ControlG, ControlB, Cause))

# Drop date 10-03-2021: Measurements taken using a different method/ under different weather
df2.bleach <- df2.bleach %>%
  filter(Date !="10-Mar-21")

# Drop date 24-06-2021: This last measurements was taken a month later instead of a week: model needs regular time intervals
#df2.bleach <- df2.bleach %>%
#  filter(Date !="24-Jun-21")

# Drop date 27-05-2021: This is recovery, without this date, colour intensity increases linearly
#df2.bleach <- df2.bleach %>%
#  filter(Date !="27-May-21")

# Set date in proper format
df2.bleach$Date <- as.Date(df2.bleach$Date, "%d-%b-%y")

# Set time to days from start experiment
df2.bleach <- as.data.frame(append(df2.bleach,
              list(Days = yday(df2.bleach$Date) - yday(df2.bleach$Date[1])), after = 5))
df2.bleach$Days <- glmmTMB::numFactor(df2.bleach$Days)

# glmmTMB AR needs Date as a factor
df2.bleach$Date <- as.factor(df2.bleach$Date)

# Transform from 0-255 scale to 0 - 1 scale: 0 = black, 1 = white
df2.bleach$Brightness <- df2.bleach$Brightness / 255

# Summary of replicate Fragments (average & median of 4 frags per Structure: Structure becomes independent observation unit)
#df2.bleach.mean <- data_summary(df2.bleach, varname = "Brightness", 
#                                    groupnames = c("Treatment", "Structure", "Species", "Date"))

# Unique id of fragments 
#df2.bleach.mean$id <- paste(df2.bleach.mean$Structure, df2.bleach.mean$Species, sep = ".")

# glmmTMB AR needs Date as a factor
#df2.bleach.mean$Date <- as.factor(df2.bleach.mean$Date)

# glmmTMB OU needs Date as numeric
#df2.bleach.mean <- as.data.frame(append(df2.bleach.mean,
#              list(Days = yday(df2.bleach.mean$Date) - yday(df2.bleach.mean$Date[1])), after = 5))

#df2.bleach.mean$Days <- glmmTMB::numFactor(df2.bleach.mean$Days)

#Bleaching_MAP_MeanMeans <- data_summary(df2.bleach, varname = "Brightness", groupnames = c("Treatment", "Species", "Date"))

```

# Model selection
```{r model selection}

# Use beta regression as data are a form of ratio
# Use all data (16 fragments per table) and correct for pseudo-replication using random effect
# Including Date as factor/categorical predictor variable, as is allows for easier interpretation of data and no need for non-linear model/quadratic terms
# Three way interaction Treatment*Species*Date likely overfitting model, so focusing on two-way interactions instead

# Incorporating nested structure (use REML to compare using AIC)
beta.all.0 <- glmmTMB(Brightness ~ Treatment*Species + Treatment*Days + Species*Days, REML = TRUE,
           data = df2.bleach, family = list(family = "beta", link = "logit"))

beta.all.nes <- glmmTMB(Brightness ~ Treatment*Species + Treatment*Days + Species*Days + (1 | Structure), REML = TRUE,
           data = df2.bleach, family = list(family = "beta", link = "logit"))

AIC(beta.all.0, beta.all.nes) # Nested structure greatly improves AIC and accounts for independence fragments on same Structure

# Autocorrelation Dates: using ou() as this allows for uneven dates
beta.all.nes.ou <- glmmTMB(Brightness ~ Treatment*Species + Treatment*Days + Species*Days + (1 | Structure) + ou(Days + 0 | id), data = df2.bleach, family = list(family = "beta", link = "logit"))

# Allowing for variable precision (dispersion) using full nested model: Tested for all combinations (+) but showing only final
beta.all.nes.ou.d7 <- glmmTMB(Brightness ~ Treatment*Species + Treatment*Days + Species*Days + (1 | Structure) + ou(Days + 0 | id), data = df2.bleach, family = list(family = "beta", link = "logit"), dispformula = ~ Date + Species + Treatment)

# Final model results
car::Anova(beta.all.nes.ou.d7)
summary(beta.all.nes.ou.d7)

```

# Model validation
```{r model validation}

mod <- beta.all.nes.ou.d7
modOutput <- simulateResiduals(fittedModel = mod, plot = F)

op <- par(mfrow = c(2, 3), mar = c(5, 4, 1, 2))
plotResiduals(modOutput, quantreg = T, quantiles = 0.5, rank = T, smoothScatter = F)
testDispersion(modOutput)
testUniformity(modOutput)
plotResiduals(modOutput, form = df2.bleach$Treatment)
plotResiduals(modOutput, form = df2.bleach$Species)
plotResiduals(modOutput, form = df2.bleach$Date)
abline(0,0)
plot(fitted(mod) ~ df2.bleach$Brightness)
par(op)

```
# Post hoc
```{r post hoc}

HSD.TS <- emmeans(beta.all.nes.ou.d7, specs = pairwise ~ Treatment | Species, adjust = "tukey", type = "response")
HSD.TS$contrasts

HSD.TD <- emmeans(beta.all.nes.ou.d7, specs = pairwise ~ Treatment | Days, adjust = "tukey", type = "response")
HSD.TD$contrasts

```

# Plotting
```{r}

## Treatment | Species
# Get averages
summary.TS <- data_summary(df2.bleach, varname = "Brightness", groupnames = c("Treatment", "Species"))

# Post hoc letters
sigletters.TS <- multcomp::cld(HSD.TS$emmeans, alpha = 0.05, Letters = letters, decreasing = T) # get CLD

# Make order match with summary dataframe
sigletters.TS <- sigletters.TS[order(sigletters.TS$Treatment),]
sigletters.TS <- sigletters.TS %>% mutate(.group = str_squish(.group)) # remove white spaces

# Merge sig.letter dataframe into the summary dataframe
summary.TS <- cbind(summary.TS, siglet.loc = sigletters.TS$.group)

# Whole bunch of stuff to transform letters to an asterisk
summary.TS <- as.data.frame(append(summary.TS, list(wave = ifelse(summary.TS$Treatment == "Control", 1, 2)), after = 0))
summary.TS <- as.data.frame(append(summary.TS, list(id = rep(c(1,2,3,4), 2)), after = 0))              
summary.TS <- widen_panel(panel_data(summary.TS), separator = "_")
summary.TS <- as.data.frame(append(summary.TS,
              list(Star_1 = "", Star_2 = ifelse(summary.TS$siglet.loc_1 == summary.TS$siglet.loc_2, "", "*"))))
summary.TS <- as.data.frame(long_panel(summary.TS, prefix = "_", begin = 1, end = 2, label_location = "end"))

# Plot
ggplot(summary.TS, aes(x = Species, fill = Treatment, pattern = Treatment, y = Brightness))+
  geom_bar_pattern(position = position_dodge(preserve = "single"), width = 0.7, stat = "identity", pattern_color = "black",
                   pattern_fill = "black", pattern_density = 0.3, pattern_spacing = 0.03, colour = "black", size = 1,
                   aes(pattern = Treatment))+ scale_pattern_manual(values = c("none", "circle"))+
  labs(x = "Species")+
  scale_y_continuous("Brightness", breaks = c(0, 0.5, 1), label = waiver (), limits = c (0, 1))+
  geom_errorbar(aes(ymin=Brightness-(1*se), ymax=Brightness+(1*se)), width=.2, size = 1, position=position_dodge(.7))+
  geom_text(data = summary.TS, aes(x=Species, y = Brightness + se, label = Star), 
            vjust= -0.5, hjust = 2.75, size = 8, fontface = "bold", position=position_dodge(.7))+
  theme_economist()+scale_colour_economist()+
  scale_x_discrete(expand = c(0, 0.75))+
  scale_y_continuous(expand = c(0, 0))+
  theme(
    axis.title.x = element_text(color = "black", vjust = 5, hjust = 0.6, size = 14),
    axis.text.x = element_text(angle = -25, hjust = 0, vjust = 1, size = 12, face = "bold"),
    axis.title.y = element_text(color = "black" , vjust = 5, size = 14),
    axis.text.y = element_text(size = 12, face = "bold", vjust = 0),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12, face = "bold"),
    plot.margin = margin(t = 10, r = 60,  b = 5,  l = 15),
    panel.background = element_rect(fill = "#FCFCFC"),
    plot.background = element_rect(fill = "#FFFFFF"),
    panel.grid.major = element_line(colour = "#797979", size = 0.2)) +
  geom_line(data = data.frame(x = c(rep(0,100)), y = seq(0,1, length.out = 100), z = factor(rep(c("Control","MAP"), 50))), 
            aes(x = x, fill = z, pattern = z, y = y, color = y, fill = x), size = 7)+
  scale_fill_manual(values=c("#FFFFFF", "#FFFFFF"))+
  scale_colour_gradientn(colours = c("#000000", "#FFFFFF"),
                         breaks  = c(0, 1),
                         limits  = c(0, 1))+
  guides(colour = "none")
ggsave("TreatmentSpecies.tiff", width = 23, height = 11, units = "cm", dpi=1200, compression = "lzw")

## Treatment | Date
# Get averages
summary.TD <- data_summary(df2.bleach, varname = "Brightness", groupnames = c("Treatment", "Date"))

# Post hoc letters
sigletters.TD <- multcomp::cld(HSD.TD$emmeans, alpha = 0.05, Letters = letters, decreasing = T) # get CLD

# Make order match with summary dataframe
sigletters.TD <- sigletters.TD[order(sigletters.TD$Treatment),]
sigletters.TD <- sigletters.TD %>% mutate(.group = str_squish(.group)) # remove white spaces

# Merge sig.letter dataframe into the summary dataframe
summary.TD <- cbind(summary.TD, siglet.loc = sigletters.TD$.group)

# Whole bunch of stuff to transform letters to an asterisk
summary.TD <- as.data.frame(append(summary.TD, list(wave = ifelse(summary.TD$Treatment == "Control", 1, 2)), after = 0))
summary.TD <- as.data.frame(append(summary.TD, list(id = rep(c(1,2,3,4,5,6,7,8,9), 2)), after = 0))              
summary.TD <- widen_panel(panel_data(summary.TD), separator = "_")
summary.TD <- as.data.frame(append(summary.TD,
              list(Star_1 = "", Star_2 = ifelse(summary.TD$siglet.loc_1 == summary.TD$siglet.loc_2, "", "*"))))
summary.TD <- as.data.frame(long_panel(summary.TD, prefix = "_", begin = 1, end = 2, label_location = "end"))

# Set date as date
summary.TD <- as.data.frame(append(summary.TD,
              list(Date2 = as.Date(strptime(as.character(summary.TD$Date), "%Y-%m-%d"), format = "%Y-%m-%d"))))

# Plot
ggplot(summary.TD, aes(x = as.Date(Date2), fill = Treatment, pattern = Treatment, y = Brightness))+
  geom_bar_pattern(position = position_dodge(preserve = "single"), width = 5, stat = "identity", pattern_color = "black",
                   pattern_fill = "black", pattern_density = 0.3, pattern_spacing = 0.02, colour = "black", size = 1,
                   aes(pattern = Treatment))+ scale_pattern_manual(values = c("none", "circle"))+
  labs(x = "")+
  scale_y_continuous("Brightness", breaks = c(0, 0.5, 1), label = waiver (), limits = c (0, 1))+
  geom_errorbar(aes(ymin=Brightness-(1*se), ymax=Brightness+(1*se)), width=2, size = 0.5, position=position_dodge(5))+
  geom_text(data = summary.TD, aes(x=as.Date(Date2), y = Brightness +se, label = Star), 
            vjust= -0, hjust = 1.5, size = 7, fontface = "bold", position=position_dodge(5))+
  theme_economist()+scale_colour_economist()+
  scale_y_continuous(expand = c(0, 0))+
  scale_x_date(limits = c(as.Date("2021-03-05"), as.Date("2021-07-01")), expand = c(0, 0))+
  theme(
    axis.title.x = element_text(color = "black", vjust = -1, hjust = 0.50, size = 14),
    axis.text.x = element_text(angle = -0, hjust = 0, vjust = 1, size = 12, face = "bold"),
    axis.title.y = element_text(color = "black" , vjust = 5, size = 14),
    axis.text.y = element_text(size = 12, face = "bold", vjust = 0),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12, face = "bold"),
    plot.margin = margin(t = 10, r = 0,  b = 5,  l = 15),
    panel.background = element_rect(fill = "#FCFCFC"),
    plot.background = element_rect(fill = "#FFFFFF"),
    panel.grid.major = element_line(colour = "#797979", size = 0.2)) +
  geom_line(data = data.frame(x = as.Date(c(rep("2021-03-05",100))), y = seq(0,1, length.out = 100), z = factor(rep(c("Control","MAP"), 50))), 
            aes(x = x, fill = z, pattern = z, y = y, color = y, fill = x), size = 10)+
  scale_fill_manual(values=c("#FFFFFF", "#FFFFFF"))+
  scale_colour_gradientn(colours = c("#000000", "#FFFFFF"),
                         breaks  = c(0, 1),
                         limits  = c(0, 1))+
  guides(colour = "none")
ggsave("TreatmentDate.tiff", width = 23, height = 11, units = "cm", dpi=1200, compression = "lzw")




```

# Check packages used
```{r package check}

knitr::purl("Mineral accretion bleaching.Rmd")
list.functions.in.file("Mineral accretion bleaching.R")
unlink("Mineral accretion bleaching.R")

```


